openapi: "3.0.2"
info:
  title: Name Game API
  version: "1.0"
servers:
  - url: http://localhost:8080/v1.0/
paths:
  /start:
    post:
      responses:
        '200':
          description: OK
  /guess:
    put:
      responses:
        '200':
          description: OK
        '400':
          description: Bad Guess
  /score:
    get:
      responses:
        '200':
          description: OK
components:
  schemas:
    Game:
      type: object
      properties:
        id:
          type: integer
          format: int64
        gameType:
          type: string
        score:
          type: integer
          format: int64
        guessId:
          type: integer
          format: int64
        tileIds:
          type: array
          items:
            $ref: '#/components/schemas/HeadShot'
        gameOver:
          type: boolean
        endTime:
          type: string
          format: date-time
    HeadShot:
      type: object
      properties:
        id:
          type: string
        alt:
          type: string
        mimeType:
          type: string
        url:
          type: string
